### ISSUE TITLE
Meythod apiinfoVersion problem

### ISSUE THREAD

**Issue by apages2** [confirm-it-solutions/PhpZabbixApi#12]
Hello,

I use the method apiinfoVersion with zabbix 2.4  and I get the error : API error -32602: The "apiinfo.version" method must be called without the "auth" parameter.

I fixed the problem by adding at line 1093 of file ZabbixApiAbstract.class.php : $this->auth = '';

Best regards

**Comment by domibarton** [comment]
Hi 

Should be fixed now in the branch'd version, can you try it again with the new files and give me some feedback?

You can find them here: https://github.com/confirm-it-solutions/PhpZabbixApi/tree/2.4

Cheers
Domi

**Comment by apages2** [comment]
Hello,

I just tested , it works

thank you

**Comment by domibarton** [comment]
OK I'll wait for the fix confirmation of issue #13, then I'll create a new tag/release.
thanks & cheers
