### ISSUE TITLE
Zabbix 2.4 HTTP Auth

### ISSUE THREAD

**Issue by ncarl** [confirm-it-solutions/PhpZabbixApi#13]
Hello,

Trying this API with Zabbix 2.4. Works great with "Internal" authentication. When I try to use HTTP authentication, it is giving me issues. 

Below are a couple tests, let me know if you have any suggestions or need me to run additional tests. Thanks!

TEST1
    $api = new ZabbixApi('https://managedhpc.x-iss.com/zabbix/api_jsonrpc.php','','','ncarl','PASSWORDHERE');

RESULT1
    API error -32602: Not authorised.

TEST2
    $api = new ZabbixApi('https://managedhpc.x-iss.com/zabbix/api_jsonrpc.php','ncarl','PASSWORDHERE','ncarl','PASSWORDHERE');

RESULT2
    Could not connect to "https://managedhpc.x-iss.com/zabbix/api_jsonrpc.php"

**Comment by domibarton** [comment]
Hi

Thanks for the report!
I found the bug, will be fixed in a few minutes!

Cheers
Domi

**Comment by domibarton** [comment]
Hi

Should be fixed now in the branch'd version, can you try it again with the new files and give me some feedback?

You can find them here: https://github.com/confirm-it-solutions/PhpZabbixApi/tree/2.4

Cheers
Domi

**Comment by ncarl** [comment]
Hi Domi,

The new branch version worked with HTTP authentication. 

Thanks!
Nick

**Comment by domibarton** [comment]
Thanks for your reply. I'll create a new tag.
