### ISSUE TITLE
Could not decode JSON response

### ISSUE THREAD

**Issue by hanzklotz** [confirm-it-solutions/PhpZabbixApi#5]
Hi,

I tried to use your php Api but after trying to connect to my zabbix server i got response "Could not decode JSON response". I have generated classes files using builder and copy those two class files to my web application directory.

here's my php script:

// load ZabbixApi
//require 'ZabbixApiAbstract.class.php';
require 'ZabbixApi.class.php';

try {

    // connect to Zabbix API
    $api = new ZabbixApi('https://zabbix.lizard.pl/api_jsonrpc.php', 'admin', 'pass');

} catch(Exception $e) {

    // Exception in ZabbixApi catched
    echo $e->getMessage();
}

and here's the error:

API request: {"jsonrpc":"2.0","method":"user.login","params":{"user":"admin","password":"pass"},"id":"14151208298496"}{"jsonrpc":"2.0","result":"6910be3f52dfc6b1df493a4b424e9510","id":"14151208298496"} Could not decode JSON response.

It looks like api connects to server and gets response but in wrong format.
Where should I search for the problem? Is your api supports connection on https?

Please help.

**Comment by domibarton** [comment]
I've updated the builder to support all Zabbix 2 versions. I've tested the build process with the Zabbix 2.2 and Zabbix 2.4 front end and the classes built successfully. But I only have a Zabbix 2.4 installation, so I couldn't really test the generated class files w/ the Zabbix 2.2 API.

I've also created new sub directories for each Zabbix version (2.2/ and 2.4) under build/ and I'll create a new tag/release as soon as the 2.2 class file is tested. For future Zabbix versions, we can build separate class files and store them next to the old ones, but as @execthis already mentioned, we should create a new tag/release as well.

@hanzklotz can you test the builder again against Zabbix 2.2 and give me some feedback?

**Comment by hanzklotz** [comment]
It's still not working. No error message this time - only blank page. On old files everything works.

**Comment by NOTOC** [comment]
Found the solution :) at least in my case.
I didn't have the api address in the server url. 
So just append api_jsonrpc.php to your zabbix url.
Like so: http://x.x.x.x/zabbix/api_jsonrpc.php
@domibarton could you please put that somewhere in the documentation, I didn't see it anywhere.

**Comment by NOTOC** [comment]
btw. thank you for phpzabbixapi. Great job.

**Comment by domibarton** [comment]
Thank you for your reply and sorry for my delay.
I'll try to update the documentation here on github.

**Comment by NOTOC** [comment]
No, thank you, and keep up the good work.

On Tue, Apr 28, 2015 at 10:42 PM, Dominique Barton <notifications@github.com
> wrote:

> Thank you for your reply and sorry for my delay.
> I'll try to update the documentation here on github.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/domibarton/PhpZabbixApi/issues/5#issuecomment-97201766>
> .
>



-- 
Lijep pozdrav,

Ivan Ravnjak


E-mail: ravnjakivan@gmail.com
GSM: 098/9123 740
MSN: ravnjakivan@gmail.com

**Comment by domibarton** [comment]
Documentation is up to date.

I've added an example on the github page on _Basic Usage_ and there's an example in the function / method annotations as well:

```php
    /**
     * @brief   Class constructor.
     *
     * @param   $apiUrl         API url (e.g. http://FQDN/zabbix/api_jsonrpc.php)
     * @param   $user           Username for Zabbix API.
     * @param   $password       Password for Zabbix API.
     * @param   $httpUser       Username for HTTP basic authorization.
     * @param   $httpPassword   Password for HTTP basic authorization.
     */

    public function __construct($apiUrl='', $user='', $password='', $httpUser='', $httpPassword='')
```
