### ISSUE TITLE
Use a stored token in a temporary location and try first before re-login

### ISSUE THREAD

**Issue by christianchristensen** [confirm-it-solutions/PhpZabbixApi#6]
Sessions (auth tokens) usually have a fairly long lifetime (default ~30 days). Re-using the token can provide a slight speed up and reduce the number of sessions created on the server (particularly for repeated auth API calls).

Perhaps a helper method for [userLogin()](https://github.com/domibarton/PhpZabbixApi/blob/60f074234767b6243482fe58442f00b150f2bfd3/build/ZabbixApiAbstract.class.php#L367-L395) that can use a temporary file storage, auth cache, and then fallback to logging in.

**Comment by domibarton** [comment]
This is a really nice idea, I'll have a look into it.

**Comment by domibarton** [comment]
# Feature implemented

## Availability 

* [latest 2.2. branch](https://github.com/confirm-it-solutions/PhpZabbixApi/tree/2.2)
* [latest 2.4 branch](https://github.com/confirm-it-solutions/PhpZabbixApi/tree/2.4)
* [2.2.1 tag / release](https://github.com/confirm-it-solutions/PhpZabbixApi/releases/tag/v2.2.1)
* [2.4.1 tag / release](https://github.com/confirm-it-solutions/PhpZabbixApi/releases/tag/v2.4.1)

## What changed

I've updated the `userLogin()` method to store / cache the auth tokens, so __no action is required__.

By default caching of auth tokens is enabled and they will be stored in the `/tmp` directory.
Here's an example:
```
/tmp/.zabbixapi-token-640c8a5376aa12fa15cf02130ce239a6
```

## Security 

All cached tokens will be stored in the filesystem, so there is _a bit_ of a security concern.

To make it _a bit more secure_, usernames in the filename will be MD5 hashed, and the file mode is set to `0600` (read-only by user).

## Change cache directory

If you want to change the path of the cache dir, set `$tokenCacheDir` to a different directory path.
Example:

```php
$params = array('user' => 'foo', 'password' => 'bar');
$api->userLogin($params, '', '/some/different/directory');
```

## Disable caching of auth tokens

If you want to disable the caching, set `$tokenCacheDir` to an empty value `''`.
Example:

```php
$params = array('user' => 'foo', 'password' => 'bar');
$api->userLogin($params, '', '');
```
